/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWasteRouteImport } from './routes/dashboard.waste'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPredictionsRouteImport } from './routes/dashboard.predictions'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard.inventory'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWasteRoute = DashboardWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPredictionsRoute = DashboardPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/waste': typeof DashboardWasteRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/waste': typeof DashboardWasteRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/waste': typeof DashboardWasteRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/inventory'
    | '/dashboard/orders'
    | '/dashboard/predictions'
    | '/dashboard/settings'
    | '/dashboard/waste'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/analytics'
    | '/dashboard/inventory'
    | '/dashboard/orders'
    | '/dashboard/predictions'
    | '/dashboard/settings'
    | '/dashboard/waste'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/inventory'
    | '/dashboard/orders'
    | '/dashboard/predictions'
    | '/dashboard/settings'
    | '/dashboard/waste'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/waste': {
      id: '/dashboard/waste'
      path: '/waste'
      fullPath: '/dashboard/waste'
      preLoaderRoute: typeof DashboardWasteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/predictions': {
      id: '/dashboard/predictions'
      path: '/predictions'
      fullPath: '/dashboard/predictions'
      preLoaderRoute: typeof DashboardPredictionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPredictionsRoute: typeof DashboardPredictionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWasteRoute: typeof DashboardWasteRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPredictionsRoute: DashboardPredictionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWasteRoute: DashboardWasteRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
